### ISSUE TITLE
STEP/STP or IGES/IGS housing files?

### ISSUE THREAD

**Issue by justinclift** [S-March/smarchWatch_PUBLIC#1]
Pretty nifty project. :smile:

With the housing files, any chance of STEP or IGES?

STL's are good for some things (eg 3D printing), but STEP or IGES include the model data, so are better for interchange with other cad software.

eg people can productively load a step or iges file in (say) FreeCAD and usefully modify it. :smile:

**Comment by amishHammer** [comment]
Even and export of the Fusion F3D file would be helpful!!

**Comment by vanbluca** [comment]
You can use the grabcad workbench to export the files in other formats really easily.

**Comment by S-March** [comment]
I should be able to export them later tonight and put them up here!

**Comment by S-March** [comment]
Didn't mean to close it. I will upload the files later tonight.

**Comment by amishHammer** [comment]
> You can use the grabcad workbench to export the files in other formats really easily.

Yeah that's only good if you have a real solid model to put into grabcad.  With just the step file you can't do much conversion.

**Comment by justinclift** [comment]
> With just the step file you can't do much conversion.

Typo?  The step file should be a solid model, whereas the stl file isn't real useful.

Well, as far as I understand anyway. :smile:

**Comment by S-March** [comment]
Sorry I am just getting to this. The step files are now committed.

**Comment by justinclift** [comment]
No worries at all @S-March, thanks for taking the time to get this stuff online. :grinning:
