### ISSUE TITLE
Boom!

### ISSUE THREAD

**Issue by zerosimms** [S-March/smarchWatch_PUBLIC#10]
This looks awesome! 
Thank you so much for sharing and congrats on the Engadget publication!

Just one question, for the PCB board, can you tell me roughly how much it will cost? Or where I should begin to find out for myself - I can see it's not an "off the shelf" component and I'm assuming I would need to provide the PCB files to a manufacturer somewhere?

Sorry for the newbie question but normally I buy off the shelf, this part is all new to me.

Cheers

**Comment by vanbluca** [comment]
I am looking into ordering a larger amount of PCBs at once to cut the costs. I already got some interested people. I expect 2pcs will be about $10 including shipping. Let me know in case you want one (or a few). I already got some interested people.

**Comment by zerosimms** [comment]
Thanks, @vanbluca - I'd be very interested in purchasing, I'll wait for you ebay link :) Cheers!
