### ISSUE TITLE
Seperate repository for Hardware, Software and other files

### ISSUE THREAD

**Issue by anselm94** [S-March/smarchWatch_PUBLIC#12]
My suggestion will be to ***create*** an **Organization**

  - Interesting name (like Pebble) for the Organisation [Tried few suggestions here](https://namelix.com/app/?keywords=walnut+watch+smart+time+color+love)

  - Create separate repositories for
    - GitHub pages website
    - Hardware
    - Software 
    - Body Design
    - miscellaneous and tutorials
    - etc.

**Comment by anselm94** [comment]
#28 Can we have seperate repository for iOS project and create a starter project for Android, for people to start contributing?

**Comment by S-March** [comment]
This is a great idea. I will look into it when I have a chance. I will close the issue for now, but please feel free to open another in the future.
