### ISSUE TITLE
Power concumption ?

### ISSUE THREAD

**Issue by JPB1JPB1** [S-March/smarchWatch_PUBLIC#21]
Great project

which is the power consumption in running mode with/without screen ?

How is it precise for the clock after one day of running , still secondes or minutes without update from other device under bluetooth ...

uSD card support for video ?

Bravo
Jp

**Comment by S-March** [comment]
Power consumption is about 6mA when the screen is off but the device is in active mode, with the screen on its about 15mA.

There is a 32K crystal on there, so it’s pretty accurate, seconds of drift if that (per day).

No uSD card, unfortunately, that takes up too much space.
