### ISSUE TITLE
Make a video showing the watch

### ISSUE THREAD

**Issue by 8lall0** [S-March/smarchWatch_PUBLIC#22]
I would love to see a video with the smarchwatch in action and i think that would be very useful :)

**Comment by vanbluca** [comment]
I recommend to mention this in issue #15 (wish list) since that topic is meant for it.

**Comment by TomasHubelbauer** [comment]
Seems to me like that issue is meant for features, this is more of a meta-issues relating to the repository IMO.

**Comment by vanbluca** [comment]
You could be right. I personally thought it was for both

**Comment by S-March** [comment]
Hey! Sure thing, do you want something different than what is in the gifs in the Imgur album?

Not much more functionality to show other than notifications and time...

**Comment by 8lall0** [comment]
Hi! sorry for being late :)

I didn't see the GIFs, their play was blocked by my phone.
They are enough, so good call on closing this "issue".

Thank you and apologies.
