### ISSUE TITLE
Not enough info on components for charger

### ISSUE THREAD

**Issue by vanbluca** [S-March/smarchWatch_PUBLIC#23]
Some of the components for the charger are not listed in the “bill of material”. For example the magnet (locks watch in place) and the (female) connector that is for the cable that goes into the charger. Perhaps other components for the charger PCB are also missing, but I am not sure about that.
Could you please add the missing info? As for the magnet could you give us at least the dimensions?

**Comment by S-March** [comment]
Yes, sorry about that! I will add it tonight when I get home.

**Comment by vanbluca** [comment]
Thx!

**Comment by vanbluca** [comment]
According to the “schematics” files, you will need the following additional components for the charger (all just 1 piece):
10118194-0001LF (609-4618-1-ND) 
ESD9B5.0ST5G (ESD9B5.0ST5GOSCT-ND)
825-22-002-10-001101 (ED10660-ND)

I recommend to wait with ordering them until @S-March confirmed. Perhaps @S-March could also tell us the dimensions of the magnet he used.

**Comment by S-March** [comment]
Those are the correct parts. Also this is the magnet I used:
https://www.amazon.com/gp/product/B074BP1FR8/

**Comment by vanbluca** [comment]
I was surprised to see you used a 32mm magnet while the space in the body is just under 30mm. I would personally go with a 30x5mm or a 25x5mm magnet.

**Comment by S-March** [comment]
There is no magnet in the actual watch. It is just in the charger.

**Comment by vanbluca** [comment]
Yes I know. I was talking about the space in the housing of the charger...
