### ISSUE TITLE
BOM doesn't have the antenna caps and inductor

### ISSUE THREAD

**Issue by bdcooke** [S-March/smarchWatch_PUBLIC#29]
I don't see the parts for C16, C17, and L2 in the BOM. In the schematic they are unlabeled, connected to the antenna. Are they unpopulated? did you just solder bridge the inductor pads?

**Comment by S-March** [comment]
That is correct. They were unneeded. The inductor pad can either be a solder blob or a 0Ohm jumper. They are 0402 size pads.
