### ISSUE TITLE
Time spent working on this

### ISSUE THREAD

**Issue by owensc84** [S-March/smarchWatch_PUBLIC#3]
Great project!  That turned out really well.  I am curious how long it took you to make this?   200 hours?  1000 hours?

**Comment by hkennyv** [comment]
@owensc84 he says [in this reddit comment](https://old.reddit.com/r/DIY/comments/bivyok/i_made_a_smartwatch_from_scratch/em5bo3z/) about 60 hours over 2 months.

**Comment by owensc84** [comment]
@hkennyv, thanks for sharing.  If he can develop that thing from scratch is 60 hours I want to hire him!

**Comment by S-March** [comment]
Ha! Thank you! Let me know if there is anything else I can help with. I'm going to close this out for now.
